# Generated by Django 4.0.2 on 2022-03-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorm',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
